version: '3'

services:
  spark-worker:
    # container_name: da-spark-worker
    build: .
    image: da-spark-image:latest
    environment:
      - SPARK_MASTER_IP=${SPARK_MASTER_IP}
    entrypoint: ['./entrypoint.sh', 'worker']
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    mem_limit: 1g   # Limite de 2 GB de RAM
    cpus: 0.5       # Limite de 1,5 CPUs
    networks:
      - cluster-network

volumes:
  spark-logs:

networks:
  cluster-network:
    driver: bridge
    ipam: 
      config:
        - subnet: 192.168.1.0/24
    name: cluster-network